"""empty message

Revision ID: 99f510325cc9
Revises: 9048761f4c7c
Create Date: 2021-08-27 01:05:30.289813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99f510325cc9'
down_revision = '9048761f4c7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empleado',
    sa.Column('ci', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=50), nullable=True),
    sa.Column('nombre_completo', sa.String(), nullable=False),
    sa.Column('correo', sa.String(), nullable=False),
    sa.Column('contrasena', sa.String(length=200), nullable=False),
    sa.Column('tlf', sa.String(), nullable=True),
    sa.Column('direccion', sa.String(length=120), nullable=True),
    sa.Column('fecha_nacimiento', sa.String(), nullable=True),
    sa.Column('sexo', sa.String(), nullable=True),
    sa.Column('estado', sa.SmallInteger(), nullable=False),
    sa.Column('dept_id', sa.Integer(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('ci_s', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ci_s'], ['empleado.ci'], ),
    sa.ForeignKeyConstraint(['dept_id'], ['departamento.id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id'], ),
    sa.PrimaryKeyConstraint('ci'),
    sa.UniqueConstraint('ci'),
    sa.UniqueConstraint('public_id')
    )
    op.create_foreign_key(None, 'historial', 'empleado', ['ci_e'], ['ci'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'historial', type_='foreignkey')
    op.drop_table('empleado')
    # ### end Alembic commands ###
