"""empty message

Revision ID: a645ff06ceda
Revises: 7cabb38a511d
Create Date: 2021-08-16 15:13:08.692097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a645ff06ceda'
down_revision = '7cabb38a511d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_dept', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_rol', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empleado',
    sa.Column('ci', sa.Integer(), nullable=False),
    sa.Column('nombre_completo', sa.String(), nullable=False),
    sa.Column('correo', sa.String(), nullable=False),
    sa.Column('contrasena', sa.String(), nullable=False),
    sa.Column('tlf', sa.String(), nullable=True),
    sa.Column('direccion', sa.String(length=120), nullable=True),
    sa.Column('fecha_nacimiento', sa.String(), nullable=True),
    sa.Column('sexo', sa.String(), nullable=True),
    sa.Column('estado', sa.SmallInteger(), nullable=False),
    sa.Column('dept_id', sa.Integer(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('ci_s', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ci_s'], ['empleado.ci'], ),
    sa.ForeignKeyConstraint(['dept_id'], ['departamento.id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id'], ),
    sa.PrimaryKeyConstraint('ci'),
    sa.UniqueConstraint('ci')
    )
    op.create_table('historial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ci_e', sa.Integer(), nullable=False),
    sa.Column('modo_uso', sa.String(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ci_e'], ['empleado.ci'], ),
    sa.PrimaryKeyConstraint('id', 'ci_e'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historial')
    op.drop_table('empleado')
    op.drop_table('rol')
    op.drop_table('departamento')
    # ### end Alembic commands ###
