"""empty message

Revision ID: cf9872fe2cf9
Revises: 76d4d7155997
Create Date: 2021-08-05 19:01:49.633117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf9872fe2cf9'
down_revision = '76d4d7155997'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'empleado', ['ci'])
    op.create_foreign_key(None, 'historial', 'empleado', ['ci_e'], ['ci'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'historial', type_='foreignkey')
    op.drop_constraint(None, 'empleado', type_='unique')
    # ### end Alembic commands ###
